image: node:latest
# image: 9.5.1

test:
  stage: test
  script:
    - cd client
    # - npm test

deploy:
  stage: deploy
  script: 
    - dpl --provider=heroku --app=drp-22 --api-key=8407fa78-ecd8-40af-962c-419fad96473b
