image: node:latest

stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: node
  script: 
    - echo "Start building App"
    - npm install
    - npm build
    - echo "Build successfully!"

test:
  stage: test
  image: node
  script:
    - echo "Testing App"
    - npm install
    - CI=true npm test
    - echo "Test successfully!"

deploy:
  stage: deploy
  script: 
    - dpl --provider=heroku --app=drp-22 --api-key=9eafb28e-9370-4431-a117-ca29bf070006
