image: node:latest

build_react:
  stage: build
  script:
    - echo "Building deploy package"
    - yarn install
    - yarn build
    - echo "Build successful"
  artifacts:
    expire_in: 1 hour
    paths:
      - build
      - node_modules/

test:
  stage: test
  needs: [build_react]
  script:
    - cd client
    - npm test

deploy:
  stage: deploy
  script: 
    - dpl --provider=heroku --app=drp-22 --api-key=9eafb28e-9370-4431-a117-ca29bf070006
