image: node:latest

test:
  stage: test
  script:
    - cd client
    - npm run build
    - npm test

deploy:
  stage: deploy
  script: 
    - dpl --provider=heroku --app=drp-22 --api-key=9eafb28e-9370-4431-a117-ca29bf070006
